export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Body } from './Body'
export { default as Pricing } from './Pricing'
export { default as Footer } from './Footer'