export { default as Statistics } from './stats'
export { default as BlogSection } from './Blog'
export { default as Download } from './Download'
export { default as Partners } from './Partners'
export { default as Cookies } from './Cookie'